### ISSUE TITLE
Adding a devices to functions in CCU cause complete whipe of in ioBroker assigned devices to that function

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.hm-rega#70] opened 2019-08-11 07:17 UTC
**Describe the bug**
Adding devices to functions causes a complete whipe of all in ioBroker assigned devices to that function and only includes the ones present in the CCU.

**To Reproduce**
1)Steps to reproduce the behavior:
2) Create a function
3) Assign 1 device to that function
4) Syncronise rega (states will be mapped to that function now)
5) Add other devices to that function in ioBroker
6) Add another device to that function in the CCU
7) restart rega adapter
8) all de devices assigned to that function in step 6 are removed.

**Expected behavior**
Equal to Rooms, do only add the new device to the function and not clean all others

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
 - hm-rpc version: 1.9.19
 - hm-rega version: 2.4.5
 - JS-Controller version: 1.5.14
 - Node version: 10.16.2
 - Operating system: Ubuntu 18.04 LTS
 - CCU model: Debmatic
 - CCU firmware: 3.47.15.31

**Comment by Apollon77** [comment] 2019-08-11 07:26
Does that happen with HMIP? Do you set in hm-rpc that devices should not be deleted?

There is a known bug in HMIP itself

**Comment by foxriver76** [comment] 2019-08-11 07:27
Will look into it, could be due to the latest changes w.r.t. https://github.com/ioBroker/ioBroker.hm-rega/issues/69

**Comment by foxriver76** [comment] 2019-08-11 07:33
>  8) all de devices assigned to that function in step 6 are removed.

You mean the ones of step 5, don't you?

**Comment by foxriver76** [comment] 2019-08-11 07:47
Wrong object has been set. Thanks for reporting and well explained steps to reproduce :-)
Should be fixed now.

**Closed** 2019-08-11 07:46 UTC

**Comment by DutchmanNL** [comment] 2019-08-11 08:25
that was fast, thanks @foxriver76 tested and works !
Have a nice Sunday
